# Generated by Django 5.2.1 on 2026-05-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="User's age", null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current weight in kg', max_digits=5, null=True, verbose_name='current weight'),
        ),
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('stay_fit', 'Stay Fit')], help_text="User's fitness goal", max_length=20, null=True, verbose_name='goal'),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Goal weight in kg', max_digits=5, null=True, verbose_name='goal weight'),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="User's height", max_digits=5, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='user',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('ft', 'ft')], default='cm', help_text='Unit for height (cm or ft)', max_length=2, verbose_name='height unit'),
        ),
    ]
