# Generated by Django 5.2.1 on 2026-05-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age_user_current_weight_user_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Designates whether the user has completed their profile/fitness info registration', verbose_name='profile complete'),
        ),
    ]
