# Generated by Django 5.2.1 on 2026-05-04 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_profile_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='heart rate')),
                ('step_count', models.IntegerField(default=0, verbose_name='step count')),
                ('calories_burned', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='calories burned')),
                ('battery_level', models.IntegerField(blank=True, null=True, verbose_name='device battery level')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'health data',
                'verbose_name_plural': 'health data records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('running', 'Running'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('gym', 'Gym/Strength'), ('yoga', 'Yoga')], max_length=50)),
                ('duration_minutes', models.IntegerField()),
                ('calories_burned', models.DecimalField(decimal_places=2, max_digits=7)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
