# Generated by Django 5.2.1 on 2026-05-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_healthdata_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.DeleteModel(
            name='HealthData',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
